{
 "title": "Kafka Stream metrics template copy",
 "description": "This is a template dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "pod_container_name",
    "query": "label_values(jvm_memory_bytes_max{pod_label_source=\"kafka\"}, pod_container_name)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "content": "<h1> <center> This is a template dashboard</center> </h1> \n<br>\n<h3> Select the variable `pod_container_name` to match your application </h3>"
  },
  {
   "title": "JVM (need to have app_label in labels of prom, to be able to get the corresponding jvm)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }
  },
  {
   "title": "JVM memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{pod_container_name=\"$pod_container_name\"}",
     "legendFormat": "{{area}} of {{pod_name}}"
    },
    {
     "expr": "jvm_memory_bytes_max{pod_container_name=\"$pod_container_name\", area=\"heap\"}",
     "legendFormat": "Max {{area}} for {{pod_name}}"
    }
   ]
  },
  {
   "title": "JVM number of threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{pod_container_name=\"$pod_container_name\"}",
     "legendFormat": "Pod {{pod_name}} threads"
    }
   ]
  },
  {
   "title": "Last GC duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "java_lang_GarbageCollector_LastGcInfo_duration{pod_container_name=\"$pod_container_name\"}",
     "legendFormat": "GC {{name}}"
    }
   ]
  },
  {
   "title": "JVM cpu usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_ProcessCpuLoad{pod_container_name=\"$pod_container_name\"}",
     "legendFormat": "Pod {{pod_uid}}"
    }
   ]
  },
  { "title": "Producer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 24 },
   "content": "### [Producer Mbean documentation](https://docs.confluent.io/current/kafka/monitoring.html#producer-metrics)\n\n"
  },
  {
   "title": "Record send rate",
   "type": "graph",
   "description": "The average number of records sent per second for a topic.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_producer_global_record_send_rate{pod_container_name=\"$pod_container_name\"})\n",
     "legendFormat": "Record send rate  {{$pod_container_name}}"
    }
   ]
  },
  {
   "title": "Retry rate",
   "type": "graph",
   "description": "The average per-second number of retried record sends for a topic.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "clamp_min(sum(kafka_producer_global_record_retry_rate{pod_container_name=\"$pod_container_name\"}), 0)\n",
     "legendFormat": "Retry rate"
    }
   ]
  },
  {
   "title": "Record error rate",
   "type": "graph",
   "description": "The average per-second number of record sends that resulted in errors for a topic.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_producer_global_record_error_rate{pod_container_name=\"$pod_container_name\"})\n",
     "legendFormat": "Record error rate "
    }
   ]
  },
  { "title": "Streams", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 45 },
   "content": "### [Kafka Stream Mbean documentation](https://docs.confluent.io/current/streams/monitoring.html)"
  },
  {
   "title": "Average number of message process per second per thread",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "kafka_stream_thread_process_rate{pod_container_name=\"$pod_container_name\"}",
     "legendFormat": "{{clientId}}"
    }
   ]
  },
  {
   "title": "Processor average execution time in ms",
   "type": "graph",
   "description": "The [average | maximum] execution time in ns, for the respective operation.\n\n\nhttps://docs.confluent.io/current/streams/monitoring.html#thread-metrics",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_stream_processor_punctuate_latency_avg{pod_container_name=\"$pod_container_name\"}",
     "legendFormat": "Punctuate latency {{processorNodeId}}  {{taskId}}  {{clientId}}"
    },
    {
     "expr": "kafka_stream_processor_process_latency_avg{pod_container_name=\"$pod_container_name\"}",
     "legendFormat": "Process latency {{processorNodeId}}  {{taskId}}  {{clientId}}"
    }
   ]
  },
  {
   "title": "Thread average execution time in ms",
   "type": "graph",
   "description": "The average execution time in ms, for the respective operation, across all running tasks of this thread.\n\n\nhttps://docs.confluent.io/current/streams/monitoring.html#thread-metrics",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_stream_thread_commit_latency_avg{pod_container_name=\"$pod_container_name\"}",
     "legendFormat": "commit latency {{clientId}}"
    },
    {
     "expr": "kafka_stream_thread_poll_latency_avg{pod_container_name=\"$pod_container_name\"}",
     "legendFormat": "poll latency {{clientId}}"
    },
    {
     "expr": "kafka_stream_thread_process_latency_avg{pod_container_name=\"$pod_container_name\"}",
     "legendFormat": "process latency {{clientId}}"
    },
    {
     "expr": "kafka_stream_thread_punctuate_latency_avg{pod_container_name=\"$pod_container_name\"}",
     "legendFormat": "punctuate latency {{clientId}}"
    }
   ]
  },
  {
   "title": "Total Skipped record in the last hour",
   "type": "singlestat",
   "description": "The total number of skipped records. Malformed records are skipped for a number of reasons, depending on your configuration. In addition to incrementing this metric, Streams logs a warning for each skip, so you should check the logs to track down the reason for unexpected skips.",
   "gridPos": { "h": 9, "w": 3, "x": 12, "y": 56 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(max_over_time(kafka_stream_thread_skipped_records_total{pod_container_name=\"$pod_container_name\"}[1h]))"
    }
   ]
  },
  {
   "title": "Statestore  latencies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "kafka_stream_statestore_get_latency_avg{pod_container_name=\"$pod_container_name\"}",
     "legendFormat": "Get latency for  {{state_id}}  on task {{taskId}}"
    },
    {
     "expr": "kafka_stream_statestore_put_latency_avg{pod_container_name=\"$pod_container_name\"}",
     "legendFormat": "Put latency for  {{state_id}}  on task {{taskId}}"
    }
   ]
  },
  { "title": "Consumer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 74 },
   "content": "### [Consumer Mbean documentation](https://docs.confluent.io/current/kafka/monitoring.html#new-consumer-metrics)\n"
  },
  {
   "title": "The maximum lag in terms of number of records for any partition in this window",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "clamp_min(kafka_consumer_global_level_records_lag_max{pod_container_name=\"$pod_container_name\"}, 0 )",
     "legendFormat": "{{clientId}}"
    }
   ]
  },
  {
   "title": "Average number of bytes consumed per second",
   "type": "graph",
   "description": "The average number of bytes consumed per second.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_global_level_bytes_consumed_rate{pod_container_name=\"$pod_container_name\"}",
     "legendFormat": "{{clientId}}"
    }
   ]
  },
  {
   "title": "Average number of records in each request.",
   "type": "graph",
   "description": "The average number of records in each request.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_global_level_records_per_request_avg{pod_container_name=\"$pod_container_name\"}",
     "legendFormat": "{{clientId}}"
    }
   ]
  },
  {
   "title": "The number of fetch requests per second.",
   "type": "graph",
   "description": "The number of fetch requests per second.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 85 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_global_level_fetch_rate{pod_container_name=\"$pod_container_name\"}",
     "legendFormat": "{{clientId}}"
    }
   ]
  },
  {
   "title": "The average number of records consumed per second.",
   "type": "graph",
   "description": "The average number of records consumed per second.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_global_level_records_consumed_rate{pod_container_name=\"$pod_container_name\"}",
     "legendFormat": "{{clientId}}"
    }
   ]
  },
  {
   "title": "Consumer Join Rate",
   "type": "graph",
   "description": "The number of group joins per second. Group joining is the first phase of the rebalance protocol. A large value indicates that the consumer group is unstable and will likely be coupled with increased lag.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 94 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_group_join_rate{pod_container_name=\"$pod_container_name\"}",
     "legendFormat": "{{clientId}}"
    }
   ]
  }
 ]
}